"""add security_checked to files

Revision ID: 5281282bbc83
Revises: 78e22f922d16
Create Date: 2026-09-06 15:53:47.067758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5281282bbc83'
down_revision: Union[str, Sequence[str], None] = '78e22f922d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('security_checked', sa.Integer(), server_default='0'))
    op.execute('UPDATE files SET security_checked = 1 WHERE security_checked = 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'security_checked')
    # ### end Alembic commands ###
