"""add files table

Revision ID: 5e6ce5370710
Revises: c1d2e3f4a5b6
Create Date: 2026-08-24 13:24:27.973752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6ce5370710'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('rel_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('upload_source', sa.String(length=32), nullable=True),
    sa.Column('business_type', sa.String(length=32), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'md5', name='uq_files_user_md5')
    )
    op.create_index(op.f('ix_files_business_id'), 'files', ['business_id'], unique=False)
    op.create_index(op.f('ix_files_business_type'), 'files', ['business_type'], unique=False)
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_files_md5'), 'files', ['md5'], unique=False)
    op.create_index(op.f('ix_files_rel_path'), 'files', ['rel_path'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.drop_table('_test_write')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_test_write',
    sa.Column('x', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_rel_path'), table_name='files')
    op.drop_index(op.f('ix_files_md5'), table_name='files')
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_index(op.f('ix_files_business_type'), table_name='files')
    op.drop_index(op.f('ix_files_business_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
