"""add business_time to diaries gears weight_records

Revision ID: 78e22f922d16
Revises: aceba2144235
Create Date: 2026-09-06 12:03:44.993446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e22f922d16'
down_revision: Union[str, Sequence[str], None] = 'aceba2144235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('business_time', sa.Float(), nullable=True))
    op.add_column('gears', sa.Column('business_time', sa.Float(), nullable=True))
    op.add_column('weight_records', sa.Column('business_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weight_records', 'business_time')
    op.drop_column('gears', 'business_time')
    op.drop_column('diaries', 'business_time')
    # ### end Alembic commands ###
