"""add_trace_id_action_columns

Revision ID: 7fa1598d107c
Revises: d58ea9a5d499
Create Date: 2026-08-09 09:58:55.275397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa1598d107c'
down_revision: Union[str, Sequence[str], None] = 'd58ea9a5d499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('trace_id', sa.String(length=64), nullable=True))
    op.add_column('event_logs', sa.Column('action', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_event_logs_action'), 'event_logs', ['action'], unique=False)
    op.create_index(op.f('ix_event_logs_trace_id'), 'event_logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_trace_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_action'), table_name='event_logs')
    op.drop_column('event_logs', 'action')
    op.drop_column('event_logs', 'trace_id')
    # ### end Alembic commands ###
