"""analysis_pipeline_refactor

Revision ID: a65795d7402d
Revises: f7a8b9c0d1e2
Create Date: 2026-08-29 14:36:02.707428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65795d7402d'
down_revision: Union[str, Sequence[str], None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_video_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('playback_file_id', sa.Integer(), nullable=True),
    sa.Column('cut_info', sa.Text(), nullable=True),
    sa.Column('derivatives', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playback_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', name='uq_analysis_video_info_analysis_id')
    )
    op.create_index(op.f('ix_analysis_video_info_analysis_id'), 'analysis_video_info', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_analysis_video_info_user_id'), 'analysis_video_info', ['user_id'], unique=False)
    op.add_column(
        'analyses',
        sa.Column('status', sa.String(length=16), nullable=False, server_default='processing'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'status')
    op.drop_index(op.f('ix_analysis_video_info_user_id'), table_name='analysis_video_info')
    op.drop_index(op.f('ix_analysis_video_info_analysis_id'), table_name='analysis_video_info')
    op.drop_table('analysis_video_info')
    # ### end Alembic commands ###
