"""add client_time column to event_logs

Revision ID: d58ea9a5d499
Revises: 7ef62264427d
Create Date: 2026-08-09 09:13:03.605357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58ea9a5d499'
down_revision: Union[str, Sequence[str], None] = '7ef62264427d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('client_time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_event_logs_client_time'), 'event_logs', ['client_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_client_time'), table_name='event_logs')
    op.drop_column('event_logs', 'client_time')
    # ### end Alembic commands ###
