import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Tennis Diary 文档',
  description: 'Tennis Diary 项目文档',
  lang: 'zh-CN',
  srcExclude: ['reference/**'],
  cleanUrls: true,
  vite: {
    server: {
      host: true,
      allowedHosts: true,
    },
  },
  themeConfig: {
    nav: [
      { text: '首页', link: '/' },
      { text: '方案', link: '/plans/01-tennis-diary-迁移微信小程序分析' },
      { text: '指南', link: '/guides/01-vitepress-踩坑记录' },
    ],
    sidebar: {
      '/plans/': [
        {
          text: '分析报告',
          items: [
            { text: 'Tennis Diary 迁移微信小程序分析', link: '/plans/01-tennis-diary-迁移微信小程序分析' },
          ],
        },
        {
          text: 'Phase B1（后台）',
          collapsed: false,
          items: [
            { text: 'B1-1：FastAPI 项目初始化与目录结构', link: '/plans/02-B1-1-FastAPI项目初始化与目录结构' },
            { text: 'B1-2：核心配置模块', link: '/plans/03-B1-2-核心配置模块' },
            { text: 'B1-3：数据库模型', link: '/plans/04-B1-3-数据库模型' },
            { text: 'B1-4：基于 loguru 的日志系统', link: '/plans/05-B1-4-基于loguru的日志系统' },
            { text: 'B1-6：日记 CRUD 接口', link: '/plans/06-B1-6-日记接口' },
            { text: 'B1-7：装备 CRUD 接口', link: '/plans/07-B1-7-装备接口' },
            { text: 'B1-8：体重记录接口', link: '/plans/08-B1-8-体重记录接口' },
            { text: 'B1-9：打卡接口', link: '/plans/09-B1-9-打卡接口' },
            { text: 'B1-10：统计汇总接口', link: '/plans/10-B1-10-统计汇总接口' },
            { text: 'B1-11：文件下载接口', link: '/plans/11-B1-11-文件下载接口' },
          ],
        },
        {
          text: 'Phase B2（后台管理 API）',
          collapsed: false,
          items: [
            { text: 'B2 总纲：后台管理 API', link: '/plans/43-B2-后台管理API总纲' },
            { text: 'B2-1：管理员模型与认证', link: '/plans/44-B2-1-管理员模型与认证' },
            { text: 'B2-2：数据查看 API', link: '/plans/45-B2-2-数据查看API' },
            { text: 'B2-3：系统监控 API', link: '/plans/46-B2-3-系统监控API' },
          ],
        },
        {
          text: 'Phase Admin（后台管理前端）',
          collapsed: false,
          items: [
            { text: 'Admin 总纲：后台管理前端', link: '/plans/47-Admin-后台管理前端' },
            { text: 'Admin-1：项目初始化', link: '/plans/48-Admin-1-项目初始化' },
            { text: 'Admin-2：布局与登录', link: '/plans/49-Admin-2-布局与登录' },
            { text: 'Admin-3：仪表盘', link: '/plans/50-Admin-3-仪表盘' },
            { text: 'Admin-4：管理功能', link: '/plans/51-Admin-4-管理功能' },
            { text: 'Admin-5：数据管理', link: '/plans/52-Admin-5-数据管理' },
            { text: 'Admin-6：系统监控', link: '/plans/53-Admin-6-系统监控' },
            { text: 'Admin-7：测试与部署', link: '/plans/54-Admin-7-测试与部署' },
          ],
        },
        {
          text: 'Phase 1（小程序前端工程）',
          collapsed: false,
          items: [
            { text: 'Phase1 总纲：uni-app 小程序前端工程初始化', link: '/plans/12-Phase1-uni-app小程序前端工程初始化' },
            { text: 'Phase1-1：uni-app 工程初始化', link: '/plans/13-Phase1-1-uni-app工程初始化' },
            { text: 'Phase1-2：目录结构与 TabBar', link: '/plans/14-Phase1-2-目录结构与TabBar' },
            { text: 'Phase1-3：Tailwind CSS 集成', link: '/plans/15-Phase1-3-Tailwind集成' },
            { text: 'Phase1-4：Tailwind 自定义组件', link: '/plans/16-Phase1-4-Tailwind自定义组件' },
            { text: 'Phase1-5：types 类型迁移', link: '/plans/17-Phase1-5-types类型迁移' },
            { text: 'Phase1-6：Pinia store 搭建', link: '/plans/18-Phase1-6-PiniaStore搭建' },
            { text: 'Phase1-7：网络层封装', link: '/plans/19-Phase1-7-网络层封装' },
            { text: 'Phase1-8：对接 B1 登录流程', link: '/plans/20-Phase1-8-对接B1登录流程' },
            { text: '21：前后端 .env 配置模板', link: '/plans/21-环境变量配置模板' },
            { text: '22：前端环境变量 AppID 注入与域名白名单校验', link: '/plans/22-前端环境变量-AppID与域名白名单校验' },
            { text: '23：构建警告清理 Tailwind 与 Sass 弃用警告', link: '/plans/23-构建警告清理-Tailwind与Sass弃用警告' },
            { text: '24：修复 WXSS 编译错误与联调排障', link: '/plans/24-修复wxss编译错误与联调排障' },
            { text: '25：静默登录门控 首次启动不请求后台', link: '/plans/25-静默登录门控-首次启动不请求后台' },
          ],
        },
        {
          text: 'Phase 2（小程序业务页面）',
          collapsed: false,
          items: [
            { text: 'Phase 2 总纲：业务页面实现', link: '/plans/26-Phase2-业务页面实现总纲' },
            { text: 'Phase 2-1：数据层与组件库', link: '/plans/27-Phase2-1-数据层与组件库' },
            { text: 'Phase 2-2：日记页', link: '/plans/28-Phase2-2-日记页' },
            { text: 'Phase 2-3：装备页', link: '/plans/29-Phase2-3-装备页' },
            { text: 'Phase 2-4：统计页', link: '/plans/30-Phase2-4-统计页' },
            { text: 'Phase 2-5：我的页', link: '/plans/31-Phase2-5-我的页' },
          ],
        },
        {
          text: '小程序优化与修复',
          collapsed: false,
          items: [
            { text: '32：Tailwind 适配方案迁移 weapp-tailwindcss', link: '/plans/32-Tailwind适配方案迁移-weapp-tailwindcss' },
            { text: '33：未登录友好提示 网络层门控与数据层兜底', link: '/plans/33-未登录友好提示-网络层门控与数据层兜底' },
            { text: '34：空数据处理完善 统计页数据总览空态', link: '/plans/34-空数据处理完善-统计页数据总览空态' },
            { text: '35：游客模式 未登录不发请求与游客引导', link: '/plans/35-游客模式-未登录不发请求与游客引导' },
            { text: '36：修复组件桶导出导致页面空白', link: '/plans/36-修复组件桶导出导致页面空白' },
            { text: '37：修复 config 加载路径 微信登录 appid 缺失', link: '/plans/37-修复config加载路径-微信登录appid缺失' },
            { text: '38：修复登录时序与用户资料编辑', link: '/plans/38-修复登录时序与用户资料编辑-参考tarot' },
            { text: '39：Alembic 数据库迁移接入', link: '/plans/39-Alembic数据库迁移接入' },
            { text: '40：我的页与资料详情页 tarot 化改造', link: '/plans/40-我的页与资料详情页tarot化改造' },
            { text: '41：修复登录错误提示 request ok 误弹', link: '/plans/41-修复登录错误提示-request ok误弹' },
            { text: '42：修复登录后昵称显示未登录', link: '/plans/42-修复登录后昵称显示未登录' },
            { text: '55：后台 API 响应格式统一重构', link: '/plans/55-后台API响应格式统一重构' },
            { text: '56：小程序前端视觉样式与交互适配改造', link: '/plans/56-小程序前端视觉样式与交互适配改造' },
            { text: '57：小程序前端样式方案重构 Tailwind→自定义 CSS', link: '/plans/57-小程序前端样式方案重构-Tailwind-自定义-CSS' },
            { text: '58：踩坑记录 weapp-tailwindcss 内容扫描失效', link: '/plans/58-踩坑记录-weapp-tailwindcss内容扫描失效' },
            { text: '59：小程序事件锚点与线上事件日志', link: '/plans/59-小程序事件锚点与线上事件日志' },
            { text: '59-v1.1：业务动作埋点与精确时间', link: '/plans/59-业务动作埋点与精确时间' },
            { text: '60：LineChart Canvas 修复', link: '/plans/60-LineChart-Canvas-修复' },
            { text: '60-v2：LineChart Canvas to SVG 重构', link: '/plans/60-LineChart-Canvas-to-SVG' },
            { text: '61：miniapp 构建警告修复 — Sass 与循环依赖', link: '/plans/61-miniapp构建警告修复-Sass与循环依赖' },
            { text: '69：miniapp 全局 Loading 遮罩', link: '/plans/69-miniapp全局Loading遮罩' },
            { text: '76：小程序 401 响应清除 token 内存态并引导登录', link: '/plans/76-小程序401响应清除token内存态并引导登录' },
            { text: '77：小程序 AI 分析 chooseVideo 选视频失败修复', link: '/plans/77-小程序AI分析chooseVideo选视频失败修复' },
          ],
        },
        {
          text: '后台管理端优化',
          collapsed: false,
          items: [
            { text: '62：Admin 事件日志详情弹窗', link: '/plans/62-Admin事件日志详情弹窗' },
            { text: '68：Admin 全局 Loading 与防重复提交', link: '/plans/68-Admin全局Loading与防重复提交' },
            { text: '70：Admin 日记/装备/体重点击查看详情', link: '/plans/70-Admin-日记装备体重点击查看' },
            { text: '71：Admin Cloudflare Workers 部署', link: '/plans/71-Admin-Cloudflare-Workers-部署' },
            { text: '72：Admin 备份管理增强', link: '/plans/72-Admin-备份管理增强' },
            { text: '74：日志查看倒序分页优化', link: '/plans/74-日志查看倒序分页优化' },
            { text: '78：动态配置系统与 Admin 配置页', link: '/plans/78-动态配置系统与Admin配置页' },
            { text: '79：AI 服务商管理 + 配置直选', link: '/plans/79-AI服务商管理配置直选' },
            { text: '80：AI 服务商多模型支持', link: '/plans/80-AI服务商多模型与模型直选' },
            { text: '81：AI 模型可用性校验与调试脚本', link: '/plans/81-AI模型可用性校验与调试脚本' },
            { text: '86：Admin 静态文件端点移除认证', link: '/plans/86-Admin静态文件端点移除认证' },
            { text: '87：Admin 时间显示统一东八区', link: '/plans/87-Admin时间显示统一东八区' },
          ],
        },
        {
          text: 'Server 部署方案',
          collapsed: false,
          items: [
            { text: '63：Docker 与 HF Space（已归档）', link: '/plans/63-Server部署方案-Docker与HF-Space' },
            { text: '64：Oracle Cloud（待建 VM 启用）', link: '/plans/64-Server部署方案-Oracle-Cloud' },
            { text: '65：魔搭创空间（当前启用）', link: '/plans/65-Server部署方案-ModelScope-创空间' },
            { text: '66：ModelScope 部署鉴权头兼容改造', link: '/plans/66-ModelScope部署鉴权头兼容改造' },
          ],
        },
        {
          text: '前端跨域代理',
          collapsed: false,
          items: [
            { text: '67：Cloudflare Workers 代理 ModelScope', link: '/plans/67-Cloudflare-Workers-代理-ModelScope-方案' },
          ],
        },
        {
          text: '测试与工程优化',
          collapsed: false,
          items: [
            { text: '73：测试体系引入 .env.test 实现环境隔离', link: '/plans/73-测试体系引入-env-test实现环境隔离' },
            { text: '84：骨架视频多帧修复', link: '/plans/84-骨架视频多帧修复' },
            { text: '85：骨骼视频帧率自适应绘制', link: '/plans/85-骨骼视频帧率自适应绘制' },
          ],
        },
        {
          text: 'Phase B2（AI 网关三件套）',
          collapsed: false,
          items: [
            { text: '75-B2 总纲：AI 网关三件套', link: '/plans/75-B2-AI网关三件套总纲' },
            { text: '75-B2-Admin：Admin 同步 AI 网关功能', link: '/plans/75-B2-Admin同步AI网关功能' },
            { text: '75-1：AI 评分代理接口', link: '/plans/75-1-AI评分代理接口' },
            { text: '75-2：视频上传与抽帧', link: '/plans/75-2-视频上传与抽帧' },
            { text: '75-3：MediaPipe 姿态推理', link: '/plans/75-3-MediaPipe姿态推理' },
            { text: '75-4：分析报告落库与历史查询', link: '/plans/75-4-分析报告落库与历史查询' },
            { text: '75-5：Phase 4 电子教练小程序页', link: '/plans/75-5-Phase4-电子教练小程序页' },
            { text: '75-6：Phase 5 分享工坊', link: '/plans/75-6-Phase5-分享工坊' },
            { text: '82：姿态模型获取与随包打包', link: '/plans/82-姿态模型获取与随包打包' },
            { text: '83：姿态可视化与六边形雷达图', link: '/plans/83-姿态可视化与六边形雷达图' },
          ],
        },
      ],
      '/guides/': [
        {
          text: '指南',
          items: [
            { text: 'VitePress 踩坑记录', link: '/guides/01-vitepress-踩坑记录' },
          ],
        },
      ],
    },
    socialLinks: [],
  },
})
